/**
 * Auto-Generated Demo Spec
 *
 * Generated by auto-discover.mjs from project analysis.
 * Project: Recipe Discovery Platform
 * Framework: Next.js
 * Features: 
 *
 * Run: npx playwright test --config=playwright.video.config.ts --grep @auto-demo
 *
 * @tags @auto-demo
 */
import { test, type Page } from '@playwright/test';
import {
  pause,
  scenicPause,
  quickPause,
  smoothScroll,
  setViewport,
  dragAndDrop,
} from './helpers';

// ---------------------------------------------------------------------------
// Caption overlay system
// ---------------------------------------------------------------------------

const CAPTION_CSS = [
  'position:fixed',
  'bottom:0',
  'left:0',
  'right:0',
  'z-index:99999',
  'padding:20px 40px 28px',
  'background:linear-gradient(transparent 0%,rgba(0,0,0,0.15) 15%,rgba(0,0,0,0.82) 100%)',
  'color:#fff',
  'font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif',
  'font-size:20px',
  'font-weight:500',
  'line-height:1.4',
  'text-align:center',
  'letter-spacing:0.01em',
  'text-shadow:0 1px 3px rgba(0,0,0,0.5)',
  'pointer-events:none',
  'opacity:0',
  'transition:opacity 0.3s ease',
].join(';');

async function showCaption(page: Page, text: string): Promise<void> {
  await page.evaluate(([t, css]: string[]) => {
    let el = document.getElementById('demo-caption');
    if (!el) {
      el = document.createElement('div');
      el.id = 'demo-caption';
      el.style.cssText = css;
      document.body.appendChild(el);
    }
    el.textContent = t;
    el.style.opacity = '1';
  }, [text, CAPTION_CSS]);
  await page.waitForTimeout(300);
}

async function hideCaption(page: Page): Promise<void> {
  await page.evaluate(() => {
    const el = document.getElementById('demo-caption');
    if (el) el.style.opacity = '0';
  });
  await page.waitForTimeout(300);
}

async function caption(page: Page, text: string, ms = 3000): Promise<void> {
  await showCaption(page, text);
  await page.waitForTimeout(ms);
  await hideCaption(page);
}

// ---------------------------------------------------------------------------
// AUTO-GENERATED DEMO
// ---------------------------------------------------------------------------

test('@auto-demo Recipe Discovery Platform -- Full Auto-Discover Demo', async ({ page }) => {
  // =========================================================================
  // SETUP
  // =========================================================================
  await setViewport(page, 1280, 800);
  await page.goto('/');
  await page.waitForLoadState('networkidle');

  // =========================================================================
  // WELCOME
  // =========================================================================
  await caption(page, 'Welcome to Recipe Discovery Platform -- a full feature tour.', 3500);


  // =========================================================================
  // OUTRO
  // =========================================================================
  await caption(
    page,
    'Recipe Discovery Platform -- Next.js, TypeScript, Tailwind CSS. Thanks for watching.',
    4500,
  );
});
