export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  postal_v2: {
    Tables: {
      carriers: {
        Row: {
          id: string;
          code: "pex" | "vc" | "efl" | "fs";
          name: string;
          display_name: string;
          description: string | null;
          logo_url: string | null;
          website: string | null;
          support_phone: string | null;
          support_email: string | null;
          base_rate_multiplier: number;
          fuel_surcharge_multiplier: number;
          residential_delivery_fee: number;
          extended_area_surcharge: number;
          reliability_rating: number | null;
          speed_rating: number | null;
          value_rating: number | null;
          customer_service_rating: number | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: "pex" | "vc" | "efl" | "fs";
          name: string;
          display_name: string;
          description?: string | null;
          logo_url?: string | null;
          website?: string | null;
          support_phone?: string | null;
          support_email?: string | null;
          base_rate_multiplier?: number;
          fuel_surcharge_multiplier?: number;
          residential_delivery_fee?: number;
          extended_area_surcharge?: number;
          reliability_rating?: number | null;
          speed_rating?: number | null;
          value_rating?: number | null;
          customer_service_rating?: number | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: "pex" | "vc" | "efl" | "fs";
          name?: string;
          display_name?: string;
          description?: string | null;
          logo_url?: string | null;
          website?: string | null;
          support_phone?: string | null;
          support_email?: string | null;
          base_rate_multiplier?: number;
          fuel_surcharge_multiplier?: number;
          residential_delivery_fee?: number;
          extended_area_surcharge?: number;
          reliability_rating?: number | null;
          speed_rating?: number | null;
          value_rating?: number | null;
          customer_service_rating?: number | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      shipments: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          shipment_number: string | null;
          reference_number: string | null;
          po_number: string | null;
          sender_address_id: string;
          sender_contact_name: string;
          sender_contact_phone: string | null;
          sender_contact_email: string | null;
          recipient_address_id: string;
          recipient_contact_name: string;
          recipient_contact_phone: string | null;
          recipient_contact_email: string | null;
          package_type: "box" | "envelope" | "tube" | "pallet";
          weight: number;
          length: number;
          width: number;
          height: number;
          declared_value: number | null;
          contents_description: string;
          carrier_id: string | null;
          service_type_id: string | null;
          estimated_delivery: string | null;
          base_rate: number | null;
          fuel_surcharge: number;
          insurance_cost: number;
          handling_fees: number;
          taxes: number;
          total_cost: number | null;
          currency: string;
          status: "draft" | "pending_payment" | "paid" | "label_generated" | "picked_up" | "in_transit" | "delivered" | "cancelled";
          tracking_number: string | null;
          label_url: string | null;
          label_data: string | null;
          payment_id: string | null;
          pickup_id: string | null;
          special_instructions: string | null;
          internal_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          shipment_number?: string | null;
          reference_number?: string | null;
          po_number?: string | null;
          sender_address_id: string;
          sender_contact_name: string;
          sender_contact_phone?: string | null;
          sender_contact_email?: string | null;
          recipient_address_id: string;
          recipient_contact_name: string;
          recipient_contact_phone?: string | null;
          recipient_contact_email?: string | null;
          package_type: "box" | "envelope" | "tube" | "pallet";
          weight: number;
          length: number;
          width: number;
          height: number;
          declared_value?: number | null;
          contents_description: string;
          carrier_id?: string | null;
          service_type_id?: string | null;
          estimated_delivery?: string | null;
          base_rate?: number | null;
          fuel_surcharge?: number;
          insurance_cost?: number;
          handling_fees?: number;
          taxes?: number;
          total_cost?: number | null;
          currency?: string;
          status?: "draft" | "pending_payment" | "paid" | "label_generated" | "picked_up" | "in_transit" | "delivered" | "cancelled";
          tracking_number?: string | null;
          label_url?: string | null;
          label_data?: string | null;
          payment_id?: string | null;
          pickup_id?: string | null;
          special_instructions?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          shipment_number?: string | null;
          reference_number?: string | null;
          po_number?: string | null;
          sender_address_id?: string;
          sender_contact_name?: string;
          sender_contact_phone?: string | null;
          sender_contact_email?: string | null;
          recipient_address_id?: string;
          recipient_contact_name?: string;
          recipient_contact_phone?: string | null;
          recipient_contact_email?: string | null;
          package_type?: "box" | "envelope" | "tube" | "pallet";
          weight?: number;
          length?: number;
          width?: number;
          height?: number;
          declared_value?: number | null;
          contents_description?: string;
          carrier_id?: string | null;
          service_type_id?: string | null;
          estimated_delivery?: string | null;
          base_rate?: number | null;
          fuel_surcharge?: number;
          insurance_cost?: number;
          handling_fees?: number;
          taxes?: number;
          total_cost?: number | null;
          currency?: string;
          status?: "draft" | "pending_payment" | "paid" | "label_generated" | "picked_up" | "in_transit" | "delivered" | "cancelled";
          tracking_number?: string | null;
          label_url?: string | null;
          label_data?: string | null;
          payment_id?: string | null;
          pickup_id?: string | null;
          special_instructions?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
